sudo: false
language: ruby
script:
  - bundle exec rake
env:
  - SOLIDUS_BRANCH=v1.0 DB=mysql
  - SOLIDUS_BRANCH=v1.1 DB=mysql
  - SOLIDUS_BRANCH=v1.2 DB=mysql
  - SOLIDUS_BRANCH=v1.3 DB=mysql
  - SOLIDUS_BRANCH=v1.4 DB=mysql
  - SOLIDUS_BRANCH=v2.0 DB=mysql
  - SOLIDUS_BRANCH=v2.1 DB=mysql
  - SOLIDUS_BRANCH=v1.0 DB=postgres
  - SOLIDUS_BRANCH=v1.1 DB=postgres
  - SOLIDUS_BRANCH=v1.2 DB=postgres
  - SOLIDUS_BRANCH=v1.3 DB=postgres
  - SOLIDUS_BRANCH=v1.4 DB=postgres
  - SOLIDUS_BRANCH=v2.0 DB=postgres
  - SOLIDUS_BRANCH=v2.1 DB=postgres
rvm:
  - 2.3.4
before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.12.6
  - bundler --version
